[MQTT]
broker = 192.168.2.2
port = 1883
keepalive = 60

[BOM]
ftp_host = ftp.bom.gov.au
remote_dir = /anon/gen/fwo/
; Current data
data_file = IDV60901.94868.csv
; Forecast data
forecast_file = IDV10450.xml

[ECOWITT]
# Replace this address string with the exact static LAN IP assigned to your Ecowitt gateway router (GW2000)
gateway_ip = 192.168.2.231
gateway_port = 45000
api_url = https://ecowitt.net
application_key = C0F905E51C86891F729F8C7263DC6A78
user_key = 106517d5-a15b-43cc-a0bf-1f182b95063e
; Enable complete solar/rain/wind readings by setting the gateway MAC address.
mac_address = 3C:8A:1F:32:5C:BF

;api_url = https://api.ecowitt.net/api/v3/device/real_time
;application_key = "C0F905E51C86891F729F8C7263DC6A78"
;user_key = "106517d5-a15b-43cc-a0bf-1f182b95063e"
;        MAC_ADDRESS = "3C:8A:1F:32:5C:BF"

[SIGEN]
api_endpoint = https://gateway.sigenstor.com/api/v1
username = Junkmail_MWW@Internode.on.net
password = b$JJPX6!Lg8*cmr

[CHARGER]
# Replace this with the static IP address assigned to your Ocular wallbox on your local network
ip_address = 192.168.2.217
port = 502

[CBUS]
# cmqttd C-Bus network interface via ser2net
host = 192.168.2.2
port = 2000
timesync = 300
; Optional cmqttd Toolkit backup containing group labels:
; project_file = CBUS_Extracted_Config\project.cbz
project_file = WATSON_26_Feb_2026_1708_1.16.2.cbz
